
training:
    # Set random seeds that will be used during training (and validation).
    #seed_numpy: -1
    #seed_torch: -1
    problem:
        name: &name maes_baselines/serial_recall_cl
        # Size of generated input: [batch_size x sequence_length x number of control + data bits].
        control_bits: &cbits 4
        data_bits: &dbits 8
        batch_size: &bs 64
        #randomize_control_lines: True
        # Parameters denoting min and max lengths.
        min_sequence_length: 3
        max_sequence_length: 20

# This section is optional.
validation:
    problem:
        name: *name
        # Size of generated input: [batch_size x sequence_length x number of control + data bits].
        control_bits: *cbits
        data_bits: *dbits
        batch_size: 64
        # Parameters denoting min and max lengths.
        min_sequence_length: 21
        max_sequence_length: 21


testing:
    # Set random seeds that will be used during testing.
    seed_numpy: -1
    seed_torch: -1
    # Problem definition.
    problem:
        name: *name
        # Size of generated input: [batch_size x sequence_length x number of control + data bits].
        control_bits: *cbits
        data_bits: *dbits
        batch_size: 64
        # Parameters denoting min and max lengths.
        min_sequence_length: 100
        max_sequence_length: 100

    

