# Load the following (default) configs first.
default_configs: 
    configs/maes_baselines/default_mae2s.yaml, 
    configs/maes_baselines/default_problem.yaml, 
    configs/maes_baselines/default_training.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name maes_baselines/serial_recall_cl
        control_bits: &cbits 4

validation:
    problem:
        name: *name 
        control_bits: *cbits

testing:
    problem:
        name: *name 
        control_bits: *cbits

# And overwrite model parameters.
#model:
    # Save/load encoder.
    #save_encoder: True
