# Load the following (default) configs first.
default_configs: 
    configs/maes_baselines/default_maes.yaml, 
    configs/maes_baselines/default_problem.yaml, 
    configs/maes_baselines/default_training.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name maes_baselines/serial_recall_cl
    dataloader:
        num_workers: 8

validation:
    problem:
        name: *name
    dataloader:
        num_workers: 8

testing:
    problem:
        name: *name
    dataloader:
        num_workers: 8

# And overwrite model parameters.
#model:
    # Save/load encoder.
    #save_encoder: True
