default_configs:
    configs/ntm/serial_recall.yaml

# Problem parameters:
training:
    problem:
        use_mask: False

validation:
    problem:
        use_mask: False

testing:
    problem:
        use_mask: False
