# Problem parameters:
problem_train:
    name: serial_recall
    # Size of generated input: [batch_size x sequence_length x number of command and data bits].
    data_bits: &dbits 8
    control_bits: &cbits 2
    batch_size: &bs 10
    # Parameters denoting min and max lengths.
    min_sequence_length: &min_seq_len 2
    max_sequence_length: &max_seq_len 20
    bias: 0.5
    cuda: True  # The presence of the 'cuda' key is optional
    #Curriculum learning - optional.
    curriculum_learning:
        interval: 2000
        initial_max_sequence_length: 3
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 0.01

# Problem parameters:
problem_validation:
    name: serial_recall
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 1
    # Parameters denoting min and max lengths.
    min_sequence_length: 21
    max_sequence_length: 21
    bias: 0.5
    frequency: 500

# Problem parameters:
problem_test:
    name: serial_recall
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 1
    # Parameters denoting min and max lengths.
    min_sequence_length: 30
    max_sequence_length: 30
    bias: 0.5

# Model parameters:
model:
    name: ntm
    # Optional parameter: visualization.
    visualization_mode: 2
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    num_control_bits: *cbits
    num_data_bits: *dbits
    # Controller parameters.
    controller:
        name: rnn
        hidden_state_size: 20
        num_layers: 1
        non_linearity: sigmoid
    # Interface
    interface:
        num_read_heads: 1
        shift_size: 3
    # Memory parameters.
    memory:
        num_content_bits: 10
        num_addresses: -1

# Set optimizer.
optimizer:
    name: Adam
    lr: 0.01

# settings parameters
settings:
    # masked output and target
    length_loss: 100
    loss_stop: 0.0001
    max_episodes: 10000
    seed_numpy: -1
    seed_torch: -1
