# Problem parameters:
training:
    cuda: False  # The presence of the 'cuda' key is optional
    problem:
        name: &name permuted_sequential_row_mnist
        batch_size: &bs 64
        start_index: 0
        stop_index: 54999
        use_train_data: True
        mnist_folder: '~/data/mnist'
        cuda: False  # The presence of the 'cuda' key is optional
    # optimizer parameters:
    optimizer:
        # Exact name of the pytorch optimizer function
        name: Adam
        # Function arguments of the optimizer, by name
        lr: 0.01
    terminal_condition:
        loss_stop: 1.0e-5
        max_episodes: 50000

# Problem parameters:
testing:
    problem:
        name: *name
        batch_size: 64
        start_index: 0
        stop_index: 9999
        use_train_data: False
        mnist_folder: '~/data/mnist'

# Problem parameters:
validation:
    problem:
        name: *name
        batch_size: 64
        start_index: 55000
        stop_index: 59999
        use_train_data: True
        mnist_folder: '~/data/mnist'

# Model parameters:
model:
    name: thalnet
    # Controller parameters.
    context_input_size: 32
    input_size: 28  # row_size
    output_size: 10 # number of classes
    center_size_per_module: 32
    num_modules: 4
