# Load the following (default) configs first.
default_configs: 
    configs/maes_baselines/dnc/default_dnc.yaml, 
    configs/maes_baselines/default_problem.yaml, 
    configs/maes_baselines/dnc/dnc_default_training.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name SkipRecallCommandLines
        # Skip params.
        seq_start: &start 0
        skip_step: &skip 2

validation:
    problem:
        name: *name 
        seq_start: *start
        skip_step: *skip

testing:
    problem:
        name: *name 
        seq_start: *start
        skip_step: *skip
