# Load the following (default) configs first.
default_configs: 
    configs/maes_baselines/dnc/default_dnc.yaml, 
    configs/maes_baselines/default_problem.yaml, 
    configs/maes_baselines/dnc/dnc_default_training.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name SequenceComparisonCommandLines

validation:
    problem:
        name: *name 

testing:
    problem:
        name: *name 
