# Model parameters:
model:
    name: ntm
    # Optional parameter: visualization.
    visualization_mode: 2
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    num_control_bits: 3
    num_data_bits: 8
    # Controller parameters.
    controller:
        name: rnn
        hidden_state_size: 20
        num_layers: 1
        non_linearity: sigmoid
    # Interface
    interface:
        num_read_heads: 1
        shift_size: 3
        use_content_based_addressing: True
    # Memory parameters.
    memory:
        num_content_bits: 15
        num_addresses: -1