# Load the following (default) configs first.
default_configs: 
    configs/maes_baselines/ntm/default_ntm.yaml,
    configs/maes_baselines/default_problem.yaml, 
    configs/maes_baselines/default_training.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name SerialRecallCommandLines

validation:
    problem:
        name: *name 

testing:
    problem:
        name: *name 
