# Load the following (default) configs first.
default_configs:
    configs/vqa_baselines/default_shape_color_query.yaml

# Model parameters:
model:
    name: MultiHopsStackedAttentionNetwork
    use_pretrained_cnn: False
    pretrained_cnn:
        name: 'resnet18'
        num_layers: 2
    attention_layer:
        nb_nodes: 128
    classifier:
        nb_hidden_nodes: 256
    default_nb_hops: 3
