# Problem parameters:
problem_train:
    name: &name serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: &cbits 2
    data_bits: &dbits 8
    batch_size: &bs 1
    # Parameters denoting min and max lengths.
    min_sequence_length: 1
    max_sequence_length: 10
    #Parameter of curriculum learning, increase the max_sequence_length
    #every ```curriculum_learning_interval```
    curriculum_learning: True
    curriculum_learning_interval: 2000
    bias: 0.5

# Problem parameters:
problem_test:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 64
    # Parameters denoting min and max lengths.
    min_sequence_length: 100
    max_sequence_length: 100
    bias: 0.5

# Problem parameters:
problem_validation:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 10
    # Parameters denoting min and max lengths.
    min_sequence_length: 60
    max_sequence_length: 60
    bias: 0.5

# Model parameters:
model:
    name: dwm   # dynamic_working_memory
    # Input bits = [control_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits 
    data_bits: *dbits
    # Controller hidden state.
    hidden_state_dim: 5
    # Memory (?).
    memory_content_size: 10
    memory_addresses_size: -1
    # Number of heads.
    num_heads: 1
    # Addressing parameters.
    use_content_addressing: False
    shift_size: 3
    # active the plotting of the memory and attention
    plot_memory: False
    
# optimizer parameters:
optimizer:
    # Exact name of the pytorch optimizer function
    name: Adam
    # Function arguments of the optimizer, by name
    lr: 0.01

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 10
    loss_stop: 1.0e-4
    max_epochs: 20000
    seed_numpy: 0
    seed_torch: 2
