# These settings come from the LSTM serial recall baseline from the original NTM paper
# Problem parameters:
problem_train:
    name: reverse_recall
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: &cbits 2
    data_bits: &dbits 8
    batch_size: &bs 10
    # Parameters denoting min and max lengths.
    min_sequence_length: 1
    max_sequence_length: 10
    #Parameter of curriculum learning, increase the max_sequence_length
    #every ```curriculum_learning_interval```
    curriculum_learning: True
    curriculum_learning_interval: 2000
    bias: 0.5
    cuda: True

# Problem parameters:
problem_test:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 1
    # Parameters denoting min and max lengths.
    min_sequence_length: 10
    max_sequence_length: 10
    bias: 0.5

# Problem parameters:
problem_validation:
    name: reverse_recall
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 10
    # Parameters denoting min and max lengths.
    min_sequence_length: 60
    max_sequence_length: 60
    bias: 0.5

# Model parameters:
model:
    name: lstm
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits
    data_bits: *dbits
    # Controller parameters.
    num_layers: 3
    hidden_state_dim: 256

optimizer:
    name: RMSprop
    lr: 0.00003
    momentum: 0.9

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 100
    loss_stop: 0.0001
    max_episodes: 1000000
    seed_numpy: 0
    seed_torch: 2
