# Problem parameters:
problem_train:
    name: &name scratch_pad
    # Size of generated input: [batch_size x sequence_length x number of control and data bits].
    control_bits: &cbits 2
    data_bits: &dbits 8
    batch_size: 16
    # Parameters denoting min and max lengths.
    min_sequence_length: 1
    max_sequence_length: 10
    num_subseq_min: 1
    num_subseq_max: 3
    #Curriculum learning - optional.
    curriculum_learning:
        interval: 0
        initial_max_sequence_length: 5
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 10
    bias: 0.5
    cuda: True

# Problem parameters:
problem_test:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 64
    # Parameters denoting min and max lengths.
    min_sequence_length: 20
    max_sequence_length: 20
    num_subseq_min: 50
    num_subseq_max: 50
    bias: 0.5

# Problem parameters:
problem_validation:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 64
    # Parameters denoting min and max lengths.
    min_sequence_length: 20
    max_sequence_length: 20
    num_subseq_min: 5
    num_subseq_max: 5
    bias: 0.5

# Problem parameters:
problem_validation:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 64
    # Parameters denoting min and max lengths.
    min_sequence_length: 60
    max_sequence_length: 60
    bias: 0.5

# Model parameters:
model:
    name: lstm
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits
    data_bits: *dbits
    # Controller parameters.
    num_layers: 3
    hidden_state_dim: 512

# Set optimizer.
optimizer:
    name: Adam
    lr: 0.005

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 100
    loss_stop: 0.0001
    max_episodes: 100000
    seed_numpy: 0
    seed_torch: 2
