# These settings come from the LSTM serial recall baseline from the original NTM paper
# Problem parameters:
problem_train:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of command and data bits].
    data_bits: &dbits 8
    control_bits: &cbits 2
    batch_size: &bs 10
    # Parameters denoting min and max lengths. 
    min_sequence_length: &min_seq_len 1
    max_sequence_length: &max_seq_len 10
    bias: 0.5
    cuda: True  # The presence of the 'cuda' key is optional

# Problem parameters:
problem_test:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 1
    # Parameters denoting min and max lengths.
    min_sequence_length: *max_seq_len
    max_sequence_length: *max_seq_len
    bias: 0.5

# Model parameters:
model:
    name: lstm
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits
    data_bits: *dbits
    batch_size: *bs
    num_layers: 3
    hidden_state_dim: 256

optimizer:
    name: RMSprop
    lr: 0.00003
    momentum: 0.9

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 100
    loss_stop: 0.0001
    max_epochs: 1000000
    seed_numpy: 0
    seed_torch: 2
