# These settings come from the LSTM serial recall baseline from the original NTM paper
# Problem parameters:
problem_train:
    name: interruption_swap_recall
    # Size of generated input: [batch_size x sequence_length x number of control and data bits].
    control_bits: &cbits 3
    data_bits: &dbits 8
    batch_size: &bs 10
    # Parameters denoting min and max lengths.
    min_sequence_length: 1
    max_sequence_length: 10
    num_subseq_min: 1
    num_subseq_max: 4
    bias: 0.5
    num_rotation: &nrot 0.5
    cuda: True

# Problem parameters:
problem_test:
    name: interruption_swap_recall
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 1
    # Parameters denoting min and max lengths.
    min_sequence_length: 10
    max_sequence_length: 10
    num_subseq_min: 4
    num_subseq_max: 4
    bias: 0.5
    num_rotation: *nrot

# Model parameters:
model:
    name: lstm
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits
    data_bits: *dbits
    batch_size: *bs
    num_layers: 3
    hidden_state_dim: 256

optimizer:
    name: RMSprop
    lr: 0.00003
    momentum: 0.9

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 100
    loss_stop: 0.0001
    max_epochs: 1000000
    seed_numpy: 0
    seed_torch: 2
