# Problem parameters:
problem_train:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of command and data bits].
    data_bits: &dbits 8
    control_bits: &cbits 2
    batch_size: &bs 1
    # Parameters denoting min and max lengths. 
    min_sequence_length: &min_seq_len 2
    max_sequence_length: &max_seq_len 20
    bias: 0.5
    cuda: True  # The presence of the 'cuda' key is optional
    #Parameter of curriculum learning, increase the max_sequence_length
    #every ```curriculum_learning_interval```
    #Optional parameter. 0 disables it.
    #curriculum_learning_interval: 1000
    
# Problem parameters:
problem_test:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 64
    # Parameters denoting min and max lengths.
    min_sequence_length: 100
    max_sequence_length: 100
    bias: 0.5

# Problem parameters:
problem_validation:
    name: serial_recall_original
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: *cbits
    data_bits: *dbits
    batch_size: 10
    # Parameters denoting min and max lengths.
    min_sequence_length: 60
    max_sequence_length: 60
    bias: 0.5

# Model parameters:
model:
    name: ntm
    # Input bits = [command_bits, data_bits]
    # Output bits = [data_bits]
    num_control_bits: *cbits
    num_data_bits: *dbits
    # Controller parameters.
    controller:
        name: ffn
        hidden_state_size: 10
        num_layers: 1
        non_linearity: none
    # Interface
    interface:
        num_read_heads: 1
        shift_size: 3
    # Memory parameters.
    memory:
        num_content_bits: 8
        num_addresses: -1
    
optimizer:
    name: RMSprop
    lr: 0.00003
    momentum: 0.9

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 100
    loss_stop: 0.0001
    max_episodes: 1000000
    seed_numpy: 0
    seed_torch: 2
