# Problem parameters:
problem:
    name: serial_recall_simplified
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    control_bits: &cbits 2
    data_bits: &dbits 8
    batch_size: &bs 1
    # Parameters denoting min and max lengths. 
    min_sequence_length: 1
    max_sequence_length: 10
    bias: 0.5
# Model parameters:
model:
    name: dwm   # dynamic_working_memory
    # Input bits = [control_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: *cbits
    data_bits: *dbits
    batch_size: *bs
    # Controller hidden state.
    hidden_state_dim: 5
    # Memory (?).
    memory_content_size: 10
    memory_addresses_size: 60
    # Number of heads.
    num_heads: 1
    # Addressing parameters.
    use_content_addressing: False
    shift_size: 3
    
