training:
    cuda: True
    # Problem parameters:
    problem:
        name: &name clevr
        batch_size: &b 64
        settings:
            data_folder: &dir '/home/vmarois/CLEVR_v1.0' # magellan server
            set: 'train'
            dataset_variant: &var 'CLEVR'
        images:
            raw_images: False
            feature_extractor:
                cnn_model: &cnn 'resnet101'
                num_blocks: 4
        questions:
            embedding_type: &emb 'random'
            embedding_dim: 300

    # Set optimizer.
    optimizer:
        name: Adam
        lr: 1.0e-4
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 10
    # Terminal condition parameters:
    terminal_condition:
        loss_stop: 0.03
        max_episodes: 220000  # approx 20 epochs with batch_size of 64
        max_epochs: 20

    # fix the seeds
    seed_torch: 0
    seed_numpy: 0

testing:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        settings:
            data_folder: *dir
            set: 'val'
            dataset_variant: *var
            images:
                raw_images: False
                feature_extractor:
                    cnn_model: *cnn
                    num_blocks: 4
            questions:
                embedding_type: *emb
                embedding_dim: 300

validation:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        settings:
            data_folder: *dir
            set: 'val'
            dataset_variant: *var
        images:
            raw_images: False
            feature_extractor:
                cnn_model: *cnn
                num_blocks: 4
        questions:
            embedding_type: *emb
            embedding_dim: 300


# Model parameters:
model:
    name: mac
    dim: 512
    embed_hidden: 300
    max_step: 12
    self_attention: False
    memory_gate: False
    dropout: 0.15
