training:
    # Problem parameters:
    problem:
        name: &name CLEVR
        batch_size: &b 64
        settings:
            data_folder: &dir '~/data/CLEVR_CoGenT_v1.0'
            set: 'trainA'
            dataset_variant: &var 'CLEVR-CoGenT'
        images:
            raw_images: False
            feature_extractor:
                cnn_model: &cnn 'resnet101'
                num_blocks: 4
        questions:
            embedding_type: &emb 'random'
            embedding_dim: 300
            embedding_source: &embsource 'CLEVR-CoGenT'
            tasks: ['Exist', 'Count', 'CompareInteger', 'CompareAttribute', 'QueryAttribute']
    sampler:
        name: 'SubsetRandomSampler'
        indices: '~/data/CLEVR_CoGenT_v1.0/vigil_cogent_train_set_indices.txt'

    # Set optimizer.
    optimizer:
        name: Adam
        lr: 1.0e-4
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 10
    # Terminal condition parameters:
    terminal_conditions:
        #loss_stop: 0.03
        epoch_limit: 20

    # fix the seeds
    seed_torch: 0
    seed_numpy: 0

validation:
    partial_validation_interval: 200
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        settings:
            data_folder: *dir
            set: 'trainA'
            dataset_variant: *var
        images:
            raw_images: False
            feature_extractor:
                cnn_model: *cnn
                num_blocks: 4
        questions:
            embedding_type: *emb
            embedding_dim: 300
            embedding_source: *embsource
            tasks: ['Exist', 'Count', 'CompareInteger', 'CompareAttribute', 'QueryAttribute']
    sampler:
        name: 'SubsetRandomSampler'
        indices: '~/data/CLEVR_CoGenT_v1.0/vigil_cogent_val_set_indices.txt'

testing:
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        settings:
            data_folder: *dir
            set: 'valA'
            dataset_variant: *var
        images:
            raw_images: False
            feature_extractor:
                cnn_model: *cnn
                num_blocks: 4
        questions:
            embedding_type: *emb
            embedding_dim: 300
            embedding_source: *embsource
            tasks: ['Exist', 'Count', 'CompareInteger', 'CompareAttribute', 'QueryAttribute']
        max_test_episodes: -1  # do an entire epoch.
