# Model parameters:
model:
    name: MAES
    # Pass the whole state from encoder to solver cell.
    pass_cell_state: True
    # Controller parameters.
    controller:
        name: RNNController
        hidden_state_size: 20
        num_layers: 1
        non_linearity: sigmoid
    # Interface
    mae_interface:
        shift_size: 3
    mas_interface:
        shift_size: 3
    # Memory parameters.
    memory:
        num_content_bits: 15
        num_addresses: -1