training:
    cuda: True
    # Problem parameters:
    problem:
        name: &name shape_color_query
        batch_size: 32
        data_folder: '~/data/shape-color-query/'
        data_filename: 'training.hy'
        dataset_size: &ds 12000
        img_size: 128
        shuffle: True
        regenerate: True
        cuda: True
        use_train_data: True
    # Set optimizer.
    optimizer:
        name: Adam
        lr: 0.005
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 10
    # Terminal condition parameters:
    terminal_condition:
        loss_stop: 0.0001
        max_episodes: 100000

testing:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: 32
        data_folder: '~/data/shape-color-query/'
        data_filename: 'training.hy'
        dataset_size: *ds
        img_size: 128
        shuffle: True
        regenerate: False
        use_train_data: False

validation:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: 32
        data_folder: '~/data/shape-color-query/'
        data_filename: 'training.hy'
        dataset_size: *ds
        img_size: 128
        shuffle: True
        regenerate: False
        use_train_data: False

# Model parameters:
model:
    name: stacked_attention_vqa   # use attention visual question answering
    use_question_encoding: True

