# Problem parameters:
problem_train:
    name: &name shape_color_query
    batch_size: 64
    data_folder: '~/data/shape-color-query/'
    data_filename: 'training.hy'
    dataset_size: &ds 12000
    img_size: 128
    shuffle: True
    regenerate: False
    cuda: True
    use_train_data: True

# Problem parameters:
problem_test:
    name: *name
    batch_size: 64
    data_folder: '~/data/shape-color-query/'
    data_filename: 'training.hy'
    dataset_size: *ds
    img_size: 128
    shuffle: True
    regenerate: False
    use_train_data: False

# Problem parameters:
problem_validation:
    name: *name
    batch_size: 64
    data_folder: '~/data/shape-color-query/'
    data_filename: 'training.hy'
    dataset_size: *ds
    img_size: 128
    shuffle: True
    regenerate: False
    use_train_data: False

# Model parameters:
model:
    name: multi_hops_attention   # use attention visual question answering model


# optimizer parameters:
optimizer:
    # Exact name of the pytorch optimizer function
    name: Adam
    # Function arguments of the optimizer, by name
    lr: 0.01

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 10
    loss_stop: 1.0e-5
    max_episodes: 50000
    seed_numpy: 4354
    seed_torch: 2452
