# Problem parameters:
training:
    #seed_numpy: 4354
    #seed_torch: 2452
    problem:
        name: &name CIFAR10
        batch_size: &b 64
        use_train_data: True
        resize: [224, 224]
    # Use sampler that operates on a subset.
    sampler:
        name: SubsetRandomSampler
        indices: [0, 45000]
    # optimizer parameters:
    optimizer:
        name: Adam
        lr: 0.01
    terminal_conditions:
        loss_stop: 1.0e-5
        episode_limit: 50000

# Problem parameters:
validation:
    problem:
        name: *name
        batch_size: *b
        use_train_data: True # True because we are splitting the training set to: validation and training
        resize: [224, 224]
    # Use sampler that operates on a subset.
    sampler:
        name: SubsetRandomSampler
        indices: [45000, 50000]

# Problem parameters:
testing:
    problem:
        name: *name
        batch_size: *b
        use_train_data: False
        resize: [224, 224]

# Model parameters:
model:
    name: AlexnetWrapper
    pretrained: False
