# Training parameters:
training:
  problem:
    name: &name MNIST
    batch_size: 64
    use_train_data: True
    mnist_folder: &folder '~/data/mnist'
    resize: [32, 32]
  # Use sampler that operates on a subset.
  sampler:
    name: SubsetRandomSampler
    indices: [0, 55000]
  # optimizer parameters:
  optimizer:
    name: Adam
    lr: 0.01
  # settings parameters
  #terminal_condition:
  #  loss_stop: 1.0e-5
  #  episode_limit: 10000
  #  epoch_limit: 10

# Validation parameters:
validation:
  partial_validation_interval: 100
  problem:
    name: *name 
    batch_size: 64
    use_train_data: True
    mnist_folder: *folder
    resize: [32, 32]
  # Use sampler that operates on a subset.
  sampler:
    name: SubsetRandomSampler
    indices: [55000, 60000]

# Testing parameters:
testing:
  problem:
    name: *name
    batch_size: 10000
    use_train_data: False
    mnist_folder: *folder
    resize: [32, 32]

# Model parameters:
model:
    name: LeNet5
