# Load the following (default) configs first.
default_configs: 
    configs/dwm_baselines/dwm/default_dwm.yaml,
    configs/dwm_baselines/default_settings_dual_task.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name interruption_swap_recall
        num_rotation: &nrot 0.5

validation:
    problem:
        name: *name 
        num_rotation: *nrot

testing:
    problem:
        name: *name 
        num_rotation: *nrot

