# Load the following (default) configs first.
default_configs: 
    configs/dwm_baselines/dwm/default_dwm.yaml,
    configs/dwm_baselines/default_settings_simple_task.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name manipulation_spatial_not

validation:
    problem:
        name: *name 

testing:
    problem:
        name: *name 
