# Load the following (default) configs first.
default_configs: 
    configs/dwm_baselines/dwm/default_dwm.yaml,
    configs/dwm_baselines/default_settings_dual_task.yaml

# Then overwrite problem name(s).
training:
    cuda: False
    problem:
        name: &name scratch_pad
        control_bits: &cbits 2

validation:
    cuda: False
    problem:
        name: *name 
        control_bits: *cbits

testing:
    cuda: False
    problem:
        name: *name 
        control_bits: *cbits

model:
    control_bits: *cbits
