# Problem parameters:
training:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  initialization_only: True
  batch_size: 48
  tasks: &task all
  data_folder: '~/data/cog'
  set: train   
  use_mask: False
  # Generate hard dataset
  dataset_type: generated
  generation:
   examples_per_task: 100
   sequence_length: 8
   memory_length: 7
   max_distractors: 10
   nr_processors: 1

validation:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: *task
  data_folder: '~/data/cog'
  set: val
  use_mask: False
  # Generate hard dataset
  dataset_type: generated
  generation:
   examples_per_task: 100
   sequence_length: 8
   memory_length: 7
   max_distractors: 10
   nr_processors: 1


model:
 name: CogModel
