# Load the COG config first.
default_configs:
  configs/cog/cog_vwm.yaml

training:
  problem:
    dataset_type: &dataset_type hard

validation:
  problem:
    dataset_type: *dataset_type

testing:
  problem:
    dataset_type: *dataset_type
