# Load the COG config first.
default_configs:
  configs/cog/cog_vwm.yaml

training:
  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 2
    tasks: &tasks [SimpleCompareColor]
    set: val

  dataloader: &dataloader
    shuffle: False
    num_workers: 0


validation:
  partial_validation_interval: 1

  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 4
    tasks: *tasks

  dataloader: *dataloader


testing:
  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 8
    tasks: *tasks

  dataloader: *dataloader
