# Load the COG config first.
default_configs:
  configs/cog/cog_vwm.yaml

training:
  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 1
    tasks: &tasks [AndCompareColor]
    set: val

  dataloader: &dataloader
    shuffle: False
    num_workers: 0


validation:
  partial_validation_interval: 1

  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 400
    tasks: *tasks

  dataloader: *dataloader


testing:
  # fix the seeds
  seed_torch: 0
  seed_numpy: 0

  problem:
    batch_size: 48
    tasks: *tasks

  dataloader: *dataloader
