# Problem parameters:
training:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: &task ['AndCompareColor']
  data_folder: '~/data/cog'
  set: val
  use_mask: False
  dataset_type: canonical
  # Set optimizer.
 optimizer:
  name: Adam
  lr: 0.001
  # weight_decay: 0.00002
 gradient_clipping: 100

testing:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 64
  tasks: *task
  data_folder: '~/data/cog'
  set: test
  dataset_type: canonical

validation:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 64
  tasks: *task
  data_folder: '~/data/cog'
  set: val
  dataset_type: canonical

model:
 name: CogModel
