# Problem parameters:
training:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: [AndCompareColor, AndCompareShape , AndSimpleCompareColor AndSimpleCompareShape, CompareColor, CompareShape, Exist,ExistColor, ExistColorOf, ExistColorSpace, ExistLastColorSameShape, ExistLastObjectSameObject, ExistLastShapeSameColor, ExistShape,ExistShapeOf, ExistShapeSpace, ExistSpace, GetColor, GetColorSpace,GetShape, GetShapeSpace, SimpleCompareColor, SimpleCompareShape]
  data_folder: '~/data/cog'
  set: train
  use_mask: False
  dataset_type: canonical
  # Set optimizer.
 optimizer:
  name: Adam
  lr: 0.0002
  weight_decay: 0.00002
 gradient_clipping: 10
 terminal_conditions:
  epoch_limit: 40
  episodes: 100000000
 partial_validation_interval: 100

validation:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: [AndCompareColor, AndCompareShape , AndSimpleCompareColor,
 AndSimpleCompareShape, CompareColor, CompareShape, Exist,
 ExistColor, ExistColorOf, ExistColorSpace, ExistLastColorSameShape,
 ExistLastObjectSameObject, ExistLastShapeSameColor, ExistShape,
 ExistShapeOf, ExistShapeSpace, ExistSpace, GetColor, GetColorSpace,
 GetShape, GetShapeSpace, SimpleCompareColor, SimpleCompareShape]
  data_folder: '~/data/cog'
  set: val
  use_mask: False
  dataset_type: canonical
partial_validation_interval: 100

testing:
 cuda: True
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: [AndCompareColor, AndCompareShape , AndSimpleCompareColor,
 AndSimpleCompareShape, CompareColor, CompareShape, Exist,
 ExistColor, ExistColorOf, ExistColorSpace, ExistLastColorSameShape,
 ExistLastObjectSameObject, ExistLastShapeSameColor, ExistShape,
 ExistShapeOf, ExistShapeSpace, ExistSpace, GetColor, GetColorSpace,
 GetShape, GetShapeSpace, SimpleCompareColor, SimpleCompareShape]
  data_folder: '~/data/cog'
  set: test
  dataset_type: hard 

model:
 name: MACNetworkSequential
 dim: 128
 embed_hidden: 64
 max_step: 12
 self_attention: False
 memory_gate: False
 dropout: 0.15
 memory_pass: True
 control_pass: False


