# Load the COG config first.
default_configs:
  configs/cog/default_cog.yaml

model:
  name: MACNetworkSequential
  dim: 128
  embed_hidden: 64
  max_step: 12
  self_attention: False
  memory_gate: False
  dropout: 0.15
  memory_pass: True
  control_pass: False


