# Problem parameters:
training:
  problem:
    name: COG
    # Size of generated input: [batch_size x sequence_length x classes].
    batch_size: 48
    tasks: [Go]
    data_folder: '~/data/cog'
    set: val
    use_mask: False
    dataset_type: canonical
  # Set optimizer.
  optimizer:
    name: Adam
    lr: 0.0002
    weight_decay: 0.00002
  gradient_clipping: 10
  terminal_conditions:
    epoch_limit: 40
    episodes: 100000000

validation:
  partial_validation_interval: 100
  problem:
    name: COG
    # Size of generated input: [batch_size x sequence_length x classes].
    batch_size: 48
    tasks: [Go]
    data_folder: '~/data/cog'
    set: val
    use_mask: False
    dataset_type: canonical

testing:
 problem:
  name: COG
  # Size of generated input: [batch_size x sequence_length x classes].
  batch_size: 48
  tasks: all
  data_folder: '~/data/cog'
  set: test
  dataset_type: canonical