# Load the following (default) configs first.
default_configs: 
    configs/dwm_baselines/dnc/default_dnc.yaml,
    configs/dwm_baselines/dnc/dnc_default_settings_simple_task.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name serial_recall

validation:
    problem:
        name: *name 

testing:
    problem:
        name: *name 
