# Problem parameters:
problem_train:
    name: &name mnist
    # Size of generated input: [batch_size x sequence_length x number of control and data bits].
    batch_size: 64
    start_index: 0
    stop_index: 54999
    use_train_data: True

# Problem parameters:
problem_test:
    name: *name
    # Size of generated input: [batch_size x sequence_length x number of control + data bits].
    batch_size: 64
    start_index: 0
    stop_index: 9999
    use_train_data: False

# Problem parameters:
problem_validation:
    name: *name
    # batch size
    batch_size: 64
    start_index: 55000
    stop_index: 59999
    use_train_data: True

# Model parameters:
model:
    name: simple_cnn   # dynamic_working_memory
    # Input bits = [control_bits, data_bits]
    # Output bits = [data_bits]

# optimizer parameters:
optimizer:
    # Exact name of the pytorch optimizer function
    name: Adam
    # Function arguments of the optimizer, by name
    lr: 0.01

# settings parameters
settings:
    # masked output and target
    use_mask: True
    length_loss: 10
    loss_stop: 1.0e-5
    max_episodes: 50000
    seed_numpy: 4354
    seed_torch: 2452
