batch_settings:
    experiment_repetitions: 1 # number of experiments 
    max_concurrent_runs: 1   # number of gpus

batch_tasks:
    -
        default_configs: configs/dwm_baselines/dwm/serial_recall.yaml
        overwrite:
            problem:
                cuda: True
    -
        default_configs: configs/dwm_baselines/dwm/reverse_recall.yaml
        overwrite:
            problem:
                cuda: True
