batch_settings:
    experiment_repetitions: 2 # number of experiments 
    max_concurrent_runs: 2   # number of gpus

batch_tasks:
    [{default_configs: 'configs/stacked_attention_vqa/sort_of_clevr.yaml'}]
