training:
    cuda: True
    # Problem parameters:
    problem:
        name: &name sort_of_clevr
        batch_size: &b 64
        data_folder: '~/data/sort-of-clevr/'
        data_filename: 'training.hy'
        dataset_size: &ds 12000
        img_size: &imgs 128
        regenerate: True
        use_train_data: True
    # Set optimizer.
    optimizer:
        name: Adam
        lr: 2.5e-4
    # Optional parameter, its presence results in clipping gradient to a range (-gradient_clipping, gradient_clipping)
    gradient_clipping: 10
    # Terminal condition parameters:
    terminal_condition:
        loss_stop: 0.1
        max_episodes: 100000

testing:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        data_folder: '~/data/sort-of-clevr/'
        data_filename: 'training.hy'
        dataset_size: *ds
        img_size: *imgs
        regenerate: False
        use_train_data: False

validation:
    cuda: True
    # Problem parameters:
    problem:
        name: *name
        batch_size: *b
        data_folder: '~/data/sort-of-clevr/'
        data_filename: 'training.hy'
        dataset_size: *ds
        img_size: *imgs
        regenerate: False
        use_train_data: False


# Model parameters:
model:
    name: relational_network
    g_theta:
      input_size: 65 # (24 + 2) * 2 + 13
    f_phi:
      output_size: 10
