# Model parameters:
model:
    name: lstm
    # Input bits = [control_bits, data_bits]
    # Output bits = [data_bits]
    control_bits: 3 
    data_bits: 8
    # Controller hidden state.
    hidden_state_dim: 256
    num_layers: 1
