# Load the following (default) configs first.
default_configs: 
    configs/dwm_baselines/lstm/default_lstm.yaml,
    configs/dwm_baselines/default_settings_dual_task.yaml

# Then overwrite problem name(s).
training:
    problem:
        name: &name ScratchPadCommandLines
        # Parameters denoting min and max lengths.
        min_sequence_length: 1
        max_sequence_length: 10
        num_subseq_min: 1
        num_subseq_max: 3


validation:
    problem:
        name: *name 


testing:
    problem:
        name: *name 
